require: rubocop-rspec

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Exclude:
    - spec/**/*_spec.rb

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*.rb

Naming/MethodParameterName:
  AllowedNames:
    - 'to'
    - 'at'
    - 'on'
    - 'id'
    - 'in'
    - 'as'

Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*_spec.rb

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - bin/*
    - "*.gemspec"
    - Rakefile

AllCops:
  Exclude:
    - 'vendor/'
